Open email Story 3
iO-Academy/2024-sept-red-pandas-email-fe pull request #3
Opened 2024-10-30 11:03 UTC by vivhayles

Please review our code?

2024-10-30 11:09 UTC, ashleycoles requested changes
Excellent work with this. Just a few minor comments

2024-10-30 11:09 UTC, ashleycoles commented on src/Pages/OpenEmailPage/index.jsx
> +import { BrowserRouter, Route, Routes, Router } from "react-router-dom"
You can delete this file now, don't think it does anything

2024-10-30 11:09 UTC, ashleycoles commented on src/Components/OpenEmails/index.jsx
> +import { useEffect, useState } from "react"
Really this is your page now, can you move this into the pages folder please :)

2024-10-30 11:09 UTC, ashleycoles commented on src/Components/CloseEmailButton/index.jsx
> +function CloseEmailButton (){
Any way you can make this more re-usable? What if it was a generic button with props that allow you to set the link and the text?

2024-10-30 11:09 UTC, ashleycoles commented on src/Components/CloseEmailButton/index.jsx
> +            <button className="px-4 py-1.5 bg-gray-500 text-white rounded hover:bg-gray-600">
You probably don't need this button tag anymore, just move the classes onto the Link and go with that

2024-10-30 11:09 UTC, ashleycoles commented on src/Components/CloseEmailButton/index.jsx
> +        <div className="grid justify-items-end pt-4">
Having this container here also limits the usability of this component - I would remove it from here and instead put this code (just this div containing the button) into your OpenEmails page instead.

That way you can use this component anytime you need a button that links to a page.

2024-10-30 12:44 UTC, ashleycoles approved these changes

2024-10-31 08:27 UTC, ashleycoles requested changes

2024-10-31 08:27 UTC, ashleycoles commented on src/Components/EmailSummary/index.jsx
>          <div className={`p-4 border-b border-gray-400 border-solid flex justify-between h-25" ${read == 1 ? "bg-header-grey text-white " : ""}`}>
Just spotted there is an extra quote on this line - the one after h-25 can be deleted

2024-10-31 08:27 UTC, ashleycoles commented on src/Components/EmailSummary/index.jsx
> +            <Link to={`/emails/${id}`} onClick={<OpenEmails />}>
You should move this Link to be the parent element of this component - at the momeny only the text is clickable, but making it the parent will make the whole 'row' clickable

2024-10-31 09:44 UTC, michaelday1991 commented
All changes resolved. Ready to merge to Main! @ashleycoles

2024-10-31 10:02 UTC, ashleycoles approved these changes

2024-10-31 10:02 UTC, merged